SOURCES=\
src/Particle.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/outputWriter/VTKWriter.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/XYZWriter.cpp\
src/outputWriter/ParticleWriter.cpp\
src/BoundaryConditions.cpp\
src/ParticleGeneratorSphere.cpp\
src/ParticleGeneratorCuboid.cpp\
src/ParticleContainerN.cpp\
src/ParticleContainerLC.cpp\
src/ParticleGeneratorTest.cpp\
src/ParticleContainerTest.cpp\
src/ParticleContainerLCTest.cpp\
src/FileReader.cpp\
src/Thermostat.cpp\
src/Calculator.cpp\
src/ForceCalc.cpp\
src/ForceCalcN.cpp\
src/ForceCalcLC.cpp\
src/VelocityCalc.cpp\
src/PositionCalc.cpp\
src/XMLInput/SimulationInput.cpp\
src/XMLInput/ParseInput.cpp\
src/MolSim.cpp\

