SOURCES=\
src/Particle.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/outputWriter/VTKWriter.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/XYZWriter.cpp\
src/ParticleGenerator.cpp\
src/ParticleContainerTest.cpp\
src/ParticleGeneratorTest.cpp\
src/FileReader.cpp\
src/ParticleContainer.cpp\
src/MolSim.cpp\
